services:
  app:
    build:
      context: .
      container_name: underbot_scrapper
      dockerfile: Dockerfile
    ports:
      - "6000:8080"
    volumes:
      - ./screenshots:/app/screenshots
    restart: always