services:
  app:
    container_name: underbot_scrapper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:8080"
    volumes:
      - ./screenshots:/app/screenshots
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M